name: novasignal
description: Um aplicativo nativo para criação de documentos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ionicons: ^0.2.2
  fl_chart: ^0.65.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9

  # PDF Generation
  pdf: ^3.10.7
  
  # File handling
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  
  # EPUB Creation
  archive: ^3.4.9
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # Ícones SVG
    - assets/menu_icon.svg
    - assets/search_icon.svg
    - assets/home_icon.svg
    - assets/editor_icon.svg
    - assets/profile_icon.svg
    - assets/settings_icon.svg
    - assets/logo.png
    - assets/arrow_back_icon.svg
    - assets/calendar_icon.svg
    - assets/edit_icon.svg
    - assets/logout_icon.svg
    - assets/theme_icon.svg
    - assets/language_icon.svg
    - assets/light_theme_icon.svg
    - assets/dark_theme_icon.svg
    - assets/auto_theme_icon.svg

    # Outras pastas
    - assets/translations/