name: novasignal
description: Um aplicativo nativo para criação de documentos
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutte

  ionicons: ^0.2.2

  http: ^1.1.0
  
  # Estado e Persistência
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # Ícones SVG
    - assets/menu_icon.svg
    - assets/search_icon.svg
    - assets/home_icon.svg
    - assets/editor_icon.svg
    - assets/profile_icon.svg
    - assets/settings_icon.svg
    - assets/logo.png
    - assets/arrow_back_icon.svg
    - assets/calendar_icon.svg
    - assets/edit_icon.svg
    - assets/logout_icon.svg
    - assets/theme_icon.svg
    - assets/language_icon.svg
    - assets/light_theme_icon.svg
    - assets/dark_theme_icon.svg
    - assets/auto_theme_icon.svg

    # Outras pastas
    - assets/translations/